Fixes Issues after testing plugin with WP 5.7 RC release
rtCamp/rtMedia pull request #1728
Opened 2021-03-17 11:37 UTC by tremidkhar

This is a fix for #1726 where the `wp_localize_script()` is being called incorrectly. The `wp_localize_script()` function required an associate array as the third argument $l10n.

2021-04-15 08:17 UTC, SID177 requested changes

2021-04-15 08:17 UTC, SID177 commented on app/assets/js/rtMedia.backbone.js
> +			//$( "#" + file.id + " .plupload_file_status" ).html( rtmedia_main.rtmedia_uploading_msg + '( ' + file.percent + '% )' );
Remove this comment

2021-04-15 08:17 UTC, SID177 commented on app/main/RTMedia.php
> +		$rtmedia_bp_tpl = array();
Check phpcs here

2021-04-15 08:17 UTC, SID177 commented on app/main/RTMedia.php
> +			wp_localize_script( 'rtmedia-main', 'rtmedia_bp', array( 'template_pack' => $bp_template ) );
phpcs

2021-04-15 08:17 UTC, SID177 commented on app/main/RTMedia.php
> +		$rtmedia_main['rtmedia_lightbox_enabled'] = strval( $this->options['general_enableLightbox'] );
phpcs

2021-04-15 08:17 UTC, SID177 commented on app/main/RTMediaUploadTerms.php
> +				wp_localize_script( 'rtmedia-main', 'rtmedia_upload_terms', array( 'check_terms_message' => $general_upload_terms_error_message ) );
phpcs

2021-04-15 08:17 UTC, SID177 commented on app/main/controllers/activity/RTMediaBuddyPressActivity.php
> +			);
phpcs

2021-04-15 11:03 UTC, tremidkhar commented on app/main/RTMediaUploadTerms.php
> +				wp_localize_script( 'rtmedia-main', 'rtmedia_upload_terms', array( 'check_terms_message' => $general_upload_terms_error_message ) );
Cannot reproduce the PHPCS error.

2021-04-15 11:04 UTC, tremidkhar commented on app/main/RTMedia.php
> +			wp_localize_script( 'rtmedia-main', 'rtmedia_bp', array( 'template_pack' => $bp_template ) );
Cannot reproduce the PHPCS error.

2021-04-16 08:43 UTC, SID177 requested changes

2021-04-16 08:43 UTC, SID177 commented on app/admin/RTMediaAdmin.php
> +				);
I don't see any changes made in settings script and so it's giving console errors.

Also if the var names has changed here, does it work with all add-ons? If it doesn't work please do the same as it's done for frontend scripts.

2021-04-16 08:43 UTC, SID177 commented on app/assets/js/rtMedia.backbone.js
> +		for( var key in rtmedia_backbone ) {
```suggestion
		for ( var key in rtmedia_backbone ) {
```

2021-04-27 06:52 UTC, merged