Fixed issue of media tab is not showing in groups page
rtCamp/rtMedia pull request #1825
Opened 2022-02-07 07:43 UTC by harsh-barach

In BuddyPress version 10.0.0 Media tab is not showing in Groups page.

To generate:-

1. Update/Install BuddyPress version 10.0.0
2. Go to the Groups page with this URL. https://website_name/groups/your_group_name/
3. After this you can see in navigation menu, Media tab will not display.
4. By this PR I have fixed this issue. So, after this PR Media will appear on Groups page.

Before = https://prnt.sc/26q0ggz
After = https://prnt.sc/26q0gva

Please let me know if you need any other information on this.

2022-02-07 07:59 UTC, thebengalboy commented
@pavanpatil1 Please could you check this?

2022-02-07 13:51 UTC, pavanpatil1 commented
Checked the PR. The fix is working fine. We can merge the PR @thebengalboy @harsh-barach once code review is done. 



https://user-images.githubusercontent.com/44057535/152800457-8b91afe6-a19f-43b2-8cfa-b30a1dc1fde7.mp4

2022-02-08 06:08 UTC, kamalahmed requested changes
can you please indent the code properly to align them with other lines? Thank you?

2022-02-08 08:15 UTC, kamalahmed approved these changes
looks good 👍

2022-02-08 12:05 UTC, thebengalboy commented
@Pradeep1308 Please could you merge this PR?

2022-02-08 12:13 UTC, merged