Move html code to templates
rtCamp/rtMedia pull request #1860
Opened 2022-03-16 14:15 UTC by vishalkakadiya

2022-03-17 08:55 UTC, chandrapatel requested changes

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/RTMediaAdmin.php
> +				include RTMEDIA_PATH . 'app/admin/templates/notices/transcoder.php';
Use `require_once` because this file need to load only once so. Address it for other new templates.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/dashboard-widgets/right-now.php
> +		<li><a href="<?php echo esc_url( 'https://rtmedia.io/' ); ?>"><?php esc_html_e( 'Homepage', 'buddypress-media' ); ?></a></li>
No need to escape static URL.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/dashboard-widgets/right-now.php
> +			<a href="<?php echo esc_url( 'https://rtmedia.io/products/category/plugins/' ); ?>"><?php esc_html_e( 'Premium Addons', 'buddypress-media' ); ?></a>
No need to escape static URL.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/notices/addon-update.php
> +		<a href="<?php echo esc_url( 'https://rtmedia.io/my-account/' ); ?>" target="_blank"><?php esc_html_e( 'your account', 'buddypress-media' ); ?></a>.
No need to escape static URL.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/notices/inspirebook-release.php
> +			<a href="<?php echo esc_url( 'https://rtmedia.io/products/inspirebook/' ); ?>" target="_blank">
No need to escape static URL.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/notices/premium-addon.php
> +			$product_page = esc_url( 'https://rtmedia.io/products/?utm_source=dashboard&utm_medium=plugin&utm_campaign=buddypress-media' );
No need to escape static URL.

2022-03-17 08:55 UTC, chandrapatel commented on app/admin/templates/settings/render-option.php
> +if ( isset( $option['after_content'] ) && '' !== $option['after_content'] ) {
Only `! empty()` check would be fine.

2022-03-17 09:29 UTC, vishalkakadiya commented
@chandrapatel I have addressed your feedbacks now, thanks!

2022-03-17 10:47 UTC, chandrapatel approved these changes

2022-03-24 11:20 UTC, thebengalboy commented
Test Cases:

- Please test the branch on a new site
- Test rtMedia Core ([feature/refactor-code](https://github.com/rtCamp/rtMedia/tree/feature/refactor-code)) independently
- Test with all the individual addon installed
- Test with Premium version that we built recently

2022-06-16 11:55 UTC, Pradeep1308 commented
@pavanpatil1 Please check the PR

2022-06-20 06:26 UTC, pavanpatil1 commented
Hi @Pradeep1308, Tested the PR. It is working fine with premium also and all the reported issues observed on this PR https://github.com/rtCamp/rtMedia/issues/1866 are fixed and working fine. You can merge the PR if the code review is done.

2022-06-20 06:37 UTC, thebengalboy commented
@pavanpatil1 @Pradeep1308 Code review is already done by @chandrapatel; Do we need to have the code reviewed again? Otherwise, if everything looks good on testing, we can proceed with merging the PR.

2022-06-20 07:38 UTC, Pradeep1308 commented
@thebengalboy Everything looks good in testing, we can proceed with merging.
confirm once, then I'll merge.

2022-06-20 08:14 UTC, thebengalboy commented
@Pradeep1308 If both the review and testing are completed, we can merge the PR √ However, after the merge, @pavanpatil1 Please have an overall test on the `pre-release` branch.

2022-06-20 08:23 UTC, merged